apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pacman-channel
  namespace: pacman
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  pathname: https://github.com/redhat-gpte-devopsautomation/pacman-1
  type: Git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/subscriptions: pacman/pacman-subscription-1
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-subscription-1
  namespace: pacman
  annotations:
    apps.open-cluster-management.io/git-branch: ''
    apps.open-cluster-management.io/git-path: 'kube'
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: pacman
spec:
  channel: pacman/pacman-channel
  placement:
    placementRef:
      name: pacman-placement-1
      kind: PlacementRule
posthooks: {}
prehooks: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-placement-1
  namespace: pacman
  annotations:
  labels:
    app: pacman
spec:
  clusterSelector:
    matchLabels:
      app: pacman
